---
language: python
python: 
  - 3.6
  - 3.7
  - 3.8
  - nightly
allow_failures:
  - python: nightly

cache: pip

dist: focal
addons:
  apt:
    packages:
      - python3-pip
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install -r optional-requirements.txt
  - pip install .
script:
  - python3 -m pytest ./opexebo