---
language: python
python: 
  - 3.8
  - 3.9
  - 3.10
  - 3.11

cache: pip

dist: focal
addons:
  apt:
    packages:
      - python3-pip
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install -r optional-requirements.txt
  - pip install .
script:
  - python3 -m pytest ./opexebo
after_success: 
  - bash <(curl -s https://codecov.io/bash)